package com.tyrads.sdk.userbase.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Full `deviceData` payload sent on `initialize`. Field names, types and value formats are kept
 * identical to the other User Base SDKs so the backend sees one consistent shape.
 */
@Serializable
data class TyradsDeviceData(
    val deviceId: String,
    val device: String,
    val brand: String,
    val model: String,
    val manufacturer: String,
    val product: String,
    val fingerprint: String,
    val baseOs: String,
    val releaseVersion: String,
    val androidApiLevel: Int?,
    val build: String,
    val version: String,
    @SerialName("package") val packageName: String,
    val apiVersion: String,
    val platform: String,
    val installerStore: String,
    val installerPackageName: String,
    val osLang: String,
    val rooted: Boolean,
    val virtual: Boolean,
    val sdkVersion: String,
    val sdkPlatform: String,
    val carrierName: String,
    val supportedAbis: String,
    val cpuType: String,
    /** Total device storage (not RAM, despite the name) in decimal GB, 2 decimals. */
    val totalMemory: Double,
    val screenWidth: Int,
    val screenHeight: Int,
    val screenDensity: Float,
    val connectionType: String,
    val isVpnActive: Boolean,
    val timeZone: String,
    val timeZoneOffset: Int,
    val systemTime: Long,
    val gpu: String,
    val bluetooth: String,
    val touchSupport: String,
    val googleAppSetID: String,
    val deviceUpTime: String,
    val deviceBootTime: String,
    // Behavioral telemetry isn't tracked: always 0, but the keys must still be sent.
    val keyboardNumEvents: Int = 0,
    val keyboardScore: Int = 0,
    val clipboardNumEvents: Int = 0,
    val clipboardScore: Int = 0,
    val clickNumEvents: Int = 0,
    val mouseNumEvents: Int = 0,
    val touchNumEvents: Int = 0,
    val mcc: String,
    val mnc: String,
    val mccMnc: String,
    val countryIso: String,
    val isRoaming: String,
    val simOperatorName: String,
    val simOperator: String,
    val simCountryIso: String,
    val phoneType: String,
    val host: String,
    val tags: String,
    val type: String,
    val codename: String,
    val buildType: String,
    val buildTags: String,
    val buildSign: String?,
    val hardware: String,
    val androidId: String?,
    val serialNumber: String,
    val deviceAge: Long?,
    val cpuCores: String,
    val cpuHardware: String,
    val cpuModel: String,
    val osArch: String?,
    val maxMemory: String,
    val freeMemory: String,
    val supported32BitAbis: String,
    val supported64BitAbis: String,
    val deviceManufacturer: String,
    val deviceModel: String,
    val deviceBrand: String,
    val deviceBoard: String,
    val deviceHardware: String,
    val androidVersion: String,
    val androidSdkInt: String,
    val networkSpeed: String,
)
